{% set name = "kdtree" %}
{% set version = "0.12" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://files.pythonhosted.org/packages/e5/11/e1de508742dab41d334ac636ad3477ef5bf61f23a455feca7979d953e695/kdtree-0.12.tar.gz
  sha256: 2ff01256177884945a8b25316d86f9234849276b3b425f750aac95eff6830d79

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - kdtree

about:
  home: https://github.com/stefankoegl/kdtree
  license: ISC (ISCL)
  license_family: OTHER
  license_file: LICENSE
  summary: A Python implementation of a kd-tree
  doc_url: https://python-kdtree.readthedocs.org/
  dev_url: https://github.com/stefankoegl/kdtree

extra:
  recipe-maintainers:
    - lincrosenbach
    - kfasolin
    - nicoddemus
