travis:
  secure:
    BINSTAR_TOKEN: rQYt0szGRsaPO+kGHjMQqmZHEolULXR2e/2OrtYawquvvfVVUnZxiuB2kTqysMUXQnTyb0jxCP9OTD5PItl9ukuom58ueVn8uWqqYELu7BMPyKPr1hAmJN3TtmhbJLpTtXnAug/+FG9UitO8DcbK43Soct5gM2waCJ8q+QaE/PiyEt2kdiu5IrDdgLlyxO3kokVOaUFd7zOAP0Hw203X9wUjb4G6DQNrR84+roCzsL3naDCJiC0QWVPbsPdRvFcQxqbtCfuitwikfsPP0T9JYSJxfTHs00/DVdH13JdMAl+bdJ2zaUZi2D/+QJps8t2vnk3ZOX0nR7UTIKWzgh+piLgBZ8FF55V6Qz4mFRQFT8EW0j4ialo92zxKXPNizkawAxhKlhil1J5ZB2ALnExnUxvX0sOnBwqBvu4dgHkeWEaXmdrWWpD9ZCM/DhRl50ux0RuSoAV4aoe7UgvrANGJDDRPr0+JPAO7dWlm4U8wDdaELS8RFX6umKy5ll6qEeacnSMitvsERKoa0Mz2HBDaiGWP7KNyQ3j5AuYy8mSRF/ihJgvC35+fKyBwkO3OLMh9d3n/vG7dihJFapoPQNkMXb2O6Z8MDma2fR8BbzMyuAs2jbu3fKpo3UwGuVVJXiuGPeln5Zefj3w4zYtSKoeSB0hA0h7/cW/znsLzpuc1k+k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
